import { createInterface } from 'node:readline';
import { writeFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';

function ask(rl, question, defaultVal) {
  return new Promise(resolve => {
    const suffix = defaultVal ? ` (${defaultVal})` : '';
    rl.question(`${question}${suffix}: `, answer => {
      resolve(answer.trim() || defaultVal || '');
    });
  });
}

function cliExists(cmd) {
  try {
    execSync(`${process.platform === 'win32' ? 'where' : 'which'} ${cmd}`, { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

export async function runSetup() {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log('\n=== REMODULER SETUP ===\n');

  // 1. Check prerequisites
  console.log('Checking prerequisites...');
  const checks = [
    ['node', cliExists('node')],
    ['git', cliExists('git')],
    ['gh (GitHub CLI)', cliExists('gh')],
    ['claude', cliExists('claude')],
  ];

  for (const [name, ok] of checks) {
    console.log(`  ${ok ? 'OK' : 'MISSING'} ${name}`);
  }

  if (!checks.every(([, ok]) => ok)) {
    console.log('\nInstall missing tools before continuing.');
  }

  console.log('');

  // 2. Firebase
  const googleCreds = await ask(rl, 'Path to serviceAccountKey.json', './serviceAccountKey.json');
  const firebaseUrl = await ask(rl, 'Firebase Database URL', '');

  // 3. User
  const userId = await ask(rl, 'Firebase User ID (DEFAULT_USER_ID)', '');
  const userName = await ask(rl, 'User name (DEFAULT_USER_NAME)', '');

  // 4. Project
  const projectId = await ask(rl, 'Default Project ID', '');

  // 5. CLIs
  const cliPlanner = await ask(rl, 'CLI for Planner', 'claude');
  const cliCoder = await ask(rl, 'CLI for Coder', 'claude');
  const cliReviewer = await ask(rl, 'CLI for Reviewer', 'claude');

  // 6. Budget
  const budget = await ask(rl, 'Daily budget USD', '10');

  // 7. Review
  const maxCycles = await ask(rl, 'Max review cycles', '3');

  rl.close();

  // Generate .env
  const env = `# REMODULER CONFIG - Generated by setup
GOOGLE_APPLICATION_CREDENTIALS=${googleCreds}
FIREBASE_DATABASE_URL=${firebaseUrl}
DEFAULT_USER_ID=${userId}
DEFAULT_USER_NAME=${userName}
DEFAULT_PROJECT_ID=${projectId}

CLI_PLANNER=${cliPlanner}
CLI_CODER=${cliCoder}
CLI_REVIEWER=${cliReviewer}
CLI_ARCHITECT=${cliPlanner}

GITHUB_TOKEN=

WS_PORT=3001
API_PORT=3002

MAX_REVIEW_CYCLES=${maxCycles}
AUTO_MERGE=true
DAILY_BUDGET_USD=${budget}

RATE_LIMIT_FALLBACK=true
FALLBACK_CLI_ORDER=claude,codex,gemini
RATE_LIMIT_COOLDOWN_MINUTES=15
`;

  const envPath = '.env';
  if (existsSync(envPath)) {
    console.log('\n.env already exists. Saving as .env.generated');
    writeFileSync('.env.generated', env);
  } else {
    writeFileSync(envPath, env);
    console.log('\n.env created successfully');
  }

  console.log('\nSetup complete! Run "remoduler doctor" to verify.\n');
}
